config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  # get 'welcome/index'

  resources :welcome

  resources :codes do
    resources :correct_answers
    resources :student_answers
    resources :team_answers
    resources :discussions
  end

  resources :student_answers, only: [] do
    collection do
      post :submit
      post :save_score
    end
  end

  resources :discussions do |
|    resources :comments
  end

  resources :users

  resources :var_roles

  resources :courses do
    resources :course_users
    resources :quizzes
  end

  resources :quizzes do
    post :judge_deadline, on: :collection
    resources :codes
  end

  resources :course_users do
    collection { post :import}
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
	has_many :correct_answers, dependent: :destroy
	has_many :student_answers, dependent: :destroy
	has_many :team_answers, dependent: :destroy
	has_many :discussions, dependent: :destroy
	validates :code, presence: true
	belongs_to :quiz

	has_rich_text :code
	has_rich_text :notes

	def correct_answer
		correct_answers.find_by(isCorrect: true)
	end

	def all_correct_answer
		correct_answers.where(isCorrect: true)
	end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :discussion
  # belongs_to :course_user
  has_rich_text :body
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
	belongs_to :code
	has_rich_text :notes
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_users, dependent: :destroy
	has_many :quizzes, dependent: :destroy
	has_many :codes, through: :quizzes
	validates :course_code, uniqueness: true, presence: true
	validates :course_name, uniqueness: true, presence: true
end

app/models/course_user.rb
require 'csv'

class CourseUser < ApplicationRecord
	belongs_to :course
	# validates :uni_ID, uniqueness: true,  presence: true
	# validates :first_name, presence: true

	def self.import(file)
		CSV.foreach(file.path, headers: ['uni_ID', 'last_name', 'first_name', 'academic_program', 'team_id']).drop(1).each do |row|
	      	CourseUser.create! row.to_hash
	    end
	end
end

# CSV.foreach(file.path, headers: true) do |row|

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :code
  has_many :comments, dependent: :destroy
  has_rich_text :code
  has_rich_text :notes
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	belongs_to :course
	has_many :codes, dependent: :destroy
	has_many :student_quizzes
	enum answer_showtime: {"Immediately After Submission": 1, "After Deadline": 2, "4 Days After Deadline": 3 }

	def total_scale
		code_ids = self.codes.ids
		CorrectAnswer.where(code_id: code_ids).where(isCorrect: true).count
	end
	def judge_show
		status = "no"

		if self.answer_showtime == "Immediately After Submission"
			status = "ok"
		elsif self.answer_showtime == "After Deadline"
			status = "ok" if Time.now >= self.deadline
		elsif self.answer_showtime == "4 Days After Deadline"
			status = "ok" if Time.now >= self.deadline+4.days
		end
		status
	end
end

app/models/student_answer.rb
class StudentAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
	# before_save :set_answer_status

	# private
	# def set_answer_status
	# 	if role.blank?||variable.blank?
	# 		self.status = missing
	# 	end
	# 	right_answer = code.correct_answer
	# 	if role == right_answer.role && variable == right_answer.variable
	# 		self.status = :correct
	# 	else
	# 		self.status = :incorrect
	# 	end
	# end
end

app/models/student_quiz.rb
class StudentQuiz < ApplicationRecord
  belongs_to :quiz
end

app/models/team_answer.rb
class TeamAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]
  validates :email, uniqueness: true
	validates :username, uniqueness: true

	def email_required?
    	false
  	end

	def will_save_change_to_email?
    	false
  	end
end

app/models/var_role.rb
class VarRole < ApplicationRecord
	validates :VarRole, uniqueness: true, presence: true
	has_rich_text :example
	has_rich_text :VarRoleDescription
end

app/controllers/var_roles_controller.rb
class VarRolesController < ApplicationController
	before_action :authenticate_user!
	# def index
	# 	@var_roles = VarRole.all
	# end

	def index
		if params[:teacher] && current_user.username == '1000000'
			@var_roles = VarRole.all
			render 'index'
		elsif params[:teacher] && current_user.username != '1000000'
			render 'index_student'
		end
		if params[:student]
			@var_roles = VarRole.all
			render 'index_student'
		end
	end
	
	# def show
	# 	@var_role = VarRole.find(params[:id])
	# end
	def show	
		if params[:teacher] && current_user.username == '1000000'
				@var_role = VarRole.find(params[:id])
				render 'show'
		elsif params[:teacher] && current_user.username != '1000000'
			render 'show_student'
		end
		if params[:student]
			@var_role = VarRole.find(params[:id])
			render 'show_student'
		end
	end

	def new
		@var_role = VarRole.new
	end

	def edit
		@var_role = VarRole.find(params[:id])
	end

	def create
		@var_role = VarRole.new(var_role_params)

		if @var_role.save
			redirect_to var_roles_path(:teacher => true)
		else
			render 'new'
		end
	end

	def update
		@var_role = VarRole.find(params[:id])

		if @var_role.update(var_role_params)
			redirect_to var_roles_path(:teacher => true)
		else
			render 'edit'
		end
	end

	def destroy
		@var_role = VarRole.find(params[:id])
  		@var_role.destroy
  		redirect_to var_roles_path(:teacher => true)
	end

	private
	def var_role_params
		params.require(:var_role).permit(:VarRole, :VarRoleDescription, :example)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-primary"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-danger"
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/var_roles_helper.rb
module VarRolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/var_roles/_form.html.erb
<%= form_with model: @var_role, local: true do |form| %>

	<% if @var_role.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@var_role.errors.count, "error") %> prohibited this article from being saved:
			</h2>
			<ul>
				<% @var_role.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= form.label :VarRole, 'Variable Role' %><br>
		<%= form.text_field :VarRole %>
	</p>

	<p>
		<%= form.label :VarRoleDescription, 'Description' %><br>
		<%= form.rich_text_area :VarRoleDescription, :cols=>80, :rows=>10 %>
	</p>

	<p>
		<%= form.label :example, 'Example' %><br>
		<%= form.rich_text_area :example, :cols=>80, :rows=>10 %>
	</p>

	<p>
		<%= form.submit 'Save'%>
	</p>

<% end %>

app/views/var_roles/edit.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><%= @var_role.VarRole %></h1>

			<%= render 'form' %>

			<%= button_tag link_to 'Home', controller: 'welcome' %>
			<%= button_tag link_to 'Back', var_roles_path(:teacher => true) %>
        </div>
    </div>
</div>

			

app/views/var_roles/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1>Listing Variable Roles</h1>
			<table style="width: 60%">
				<table border ="1">
				<tr>
					<th style="width: 10%">Variable Role</th>
					<th style="width: 35%">Description</th>
					<!-- <th>Last Updated</th> -->
					<th style="width: 15%">Action</th>
				</tr>

				<% @var_roles.each do |var_role| %>
					<tr>
						<td><%= var_role.VarRole %></td>
						<td><%= var_role.VarRoleDescription %></td>
						<!-- <td><%= var_role.updated_at %></td> -->
						<td><%#= button_tag link_to 'Show Example', var_role_path(var_role, :teacher => true) %>
						<%= button_tag link_to 'Edit', edit_var_role_path(var_role) %>
						<%= button_tag link_to 'Delete', var_role_path(var_role), method: :delete, data: {confirm: 'Are you sure?'} %></td>
					</tr>
				<% end %>
			</table>
			<br>
			<%= button_tag link_to 'Back', welcome_path(teacher: true, :id => '0') %>
			<%= button_tag link_to 'Create New Variable Role', new_var_role_path %>
        </div>
    </div>
</div>

			

app/views/var_roles/index_student.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?student=true">Home</a></li>
            <li><a href="/courses?take_quiz=true">Quiz</a></li>
            <li><a href="/var_roles?student=true">Variable Roles</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1>Listing Variable Roles</h1>
			<table style="width: 60%">
				<table border ="1">
				<tr>
					<th style="width: 10%">Variable Role</th>
					<th style="width: 35%">Description</th>
					<!-- <th>Last Updated</th> -->
					<th style="width: 15%">Action</th>
				</tr>

				<% @var_roles.each do |var_role| %>
					<% quiz=Quiz.find_by_quiz_name(var_role.VarRole) %>
					<tr>
						<td><%= var_role.VarRole %></td>
						<td><%= var_role.VarRoleDescription %></td>
						<!-- <td><%= var_role.updated_at %></td> -->
						<td><%= button_tag link_to 'Show Example', var_role_path(var_role, :student => true) %>
						<%= button_tag link_to 'Review Quiz', "/quizzes/#{quiz.id}?take_quiz=true" %>
					</tr>
				<% end %>
			</table>
			<br>
			<%= button_tag link_to 'Back', welcome_path(student: true, :id => '0') %>
        </div>
    </div>
</div>

			

app/views/var_roles/new.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
          
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1>New Variable Role</h1>

			<%= render 'form' %>

			<%= button_tag link_to 'Home', controller: 'welcome' %>
			<%= button_tag link_to 'Back', var_roles_path(:teacher => true) %>
        </div>
    </div>
</div>

			

app/views/var_roles/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong><%= @var_role.VarRole %></strong></h1>
		
			<p>
				<strong>Description:</strong>
				<%= @var_role.VarRoleDescription %>
			</p>

			<p>
				<strong>Example:</strong>
				<%= @var_role.example %>
			</p>

			<p>
				<strong>Last Updated:</strong>
				<%= @var_role.updated_at %>
			</p>

			<%= button_tag link_to 'Edit', edit_var_role_path(@var_role) %>
			<%= button_tag link_to 'Back', var_roles_path(:teacher => true) %>
    
        </div>
    </div>
</div>

			

app/views/var_roles/show_student.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?student=true">Home</a></li>
            <li><a href="/courses?take_quiz=true">Quiz</a></li>
            <li><a href="/var_roles?student=true">Variable Roles</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong><%= @var_role.VarRole %></strong></h1>
			
			<p>
				<strong>Description:</strong>
				<%= @var_role.VarRoleDescription %>
			</p>

			<p>
				<strong>Example:</strong>
				<%= @var_role.example %>
			</p>

			<%= button_tag link_to 'Back', var_roles_path(:student => true) %>
      <% if @var_role.VarRole == "Fixed-value"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/26?take_quiz=true" %>
      <%= button_tag link_to 'Next', "/var_roles/13?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "Stepper"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/27?take_quiz=true" %>
      <%= button_tag link_to 'Previous', "/var_roles/12?student=true" %>
      <%= button_tag link_to 'Next', "/var_roles/14?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "Most-recent-holder"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/28?take_quiz=true" %>
      <%= button_tag link_to 'Previous', "/var_roles/13?student=true" %>
      <%= button_tag link_to 'Next', "/var_roles/15?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "Most-wanted-holder"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/29?take_quiz=true" %>
      <%= button_tag link_to 'Previous', "/var_roles/14?student=true" %>
      <%= button_tag link_to 'Next', "/var_roles/16?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "Gatherer"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/30?take_quiz=true" %>
      <%= button_tag link_to 'Previous', "/var_roles/15?student=true" %>
      <%= button_tag link_to 'Next', "/var_roles/17?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "Follower"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/31?take_quiz=true" %>
      <%= button_tag link_to 'Previous', "/var_roles/16?student=true" %>
      <%= button_tag link_to 'Next', "/var_roles/18?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "One-way-flag"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/32?take_quiz=true" %>
      <%= button_tag link_to 'Previous', "/var_roles/17?student=true" %>
      <%= button_tag link_to 'Next', "/var_roles/19?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "Temporary"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/33?take_quiz=true" %>
      <%= button_tag link_to 'Previous', "/var_roles/18?student=true" %>
      <%= button_tag link_to 'Next', "/var_roles/20?student=true" %>
      <% end %>
      <% if @var_role.VarRole == "Others"%>
      <%= button_tag link_to 'Review Quiz', "/quizzes/34?take_quiz=true" %>
      <% end %>
        </div>
    </div>
</div>

			