config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  # get 'welcome/index'

  resources :welcome

  resources :codes do
    resources :correct_answers
    resources :student_answers
    resources :team_answers
    resources :discussions
  end

  resources :student_answers, only: [] do
    collection do
      post :submit
      post :save_score
    end
  end

  resources :discussions do |
|    resources :comments
  end

  resources :users

  resources :var_roles

  resources :courses do
    resources :course_users
    resources :quizzes
  end

  resources :quizzes do
    post :judge_deadline, on: :collection
    resources :codes
  end

  resources :course_users do
    collection { post :import}
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
	has_many :correct_answers, dependent: :destroy
	has_many :student_answers, dependent: :destroy
	has_many :team_answers, dependent: :destroy
	has_many :discussions, dependent: :destroy
	validates :code, presence: true
	belongs_to :quiz

	has_rich_text :code
	has_rich_text :notes

	def correct_answer
		correct_answers.find_by(isCorrect: true)
	end

	def all_correct_answer
		correct_answers.where(isCorrect: true)
	end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :discussion
  # belongs_to :course_user
  has_rich_text :body
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
	belongs_to :code
	has_rich_text :notes
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_users, dependent: :destroy
	has_many :quizzes, dependent: :destroy
	has_many :codes, through: :quizzes
	validates :course_code, uniqueness: true, presence: true
	validates :course_name, uniqueness: true, presence: true
end

app/models/course_user.rb
require 'csv'

class CourseUser < ApplicationRecord
	belongs_to :course
	# validates :uni_ID, uniqueness: true,  presence: true
	# validates :first_name, presence: true

	def self.import(file)
		CSV.foreach(file.path, headers: ['uni_ID', 'last_name', 'first_name', 'academic_program', 'team_id']).drop(1).each do |row|
	      	CourseUser.create! row.to_hash
	    end
	end
end

# CSV.foreach(file.path, headers: true) do |row|

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :code
  has_many :comments, dependent: :destroy
  has_rich_text :code
  has_rich_text :notes
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	belongs_to :course
	has_many :codes, dependent: :destroy
	has_many :student_quizzes
	enum answer_showtime: {"Immediately After Submission": 1, "After Deadline": 2, "4 Days After Deadline": 3 }

	def total_scale
		code_ids = self.codes.ids
		CorrectAnswer.where(code_id: code_ids).where(isCorrect: true).count
	end
	def judge_show
		status = "no"

		if self.answer_showtime == "Immediately After Submission"
			status = "ok"
		elsif self.answer_showtime == "After Deadline"
			status = "ok" if Time.now >= self.deadline
		elsif self.answer_showtime == "4 Days After Deadline"
			status = "ok" if Time.now >= self.deadline+4.days
		end
		status
	end
end

app/models/student_answer.rb
class StudentAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
	# before_save :set_answer_status

	# private
	# def set_answer_status
	# 	if role.blank?||variable.blank?
	# 		self.status = missing
	# 	end
	# 	right_answer = code.correct_answer
	# 	if role == right_answer.role && variable == right_answer.variable
	# 		self.status = :correct
	# 	else
	# 		self.status = :incorrect
	# 	end
	# end
end

app/models/student_quiz.rb
class StudentQuiz < ApplicationRecord
  belongs_to :quiz
end

app/models/team_answer.rb
class TeamAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]
  validates :email, uniqueness: true
	validates :username, uniqueness: true

	def email_required?
    	false
  	end

	def will_save_change_to_email?
    	false
  	end
end

app/models/var_role.rb
class VarRole < ApplicationRecord
	validates :VarRole, uniqueness: true, presence: true
	has_rich_text :example
	has_rich_text :VarRoleDescription
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/var_roles_helper.rb
module VarRolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <div class="container">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Quizzes', courses_path(:take_quiz => true), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Variable Roles', var_roles_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</header>