config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  # get 'welcome/index'

  resources :welcome

  resources :codes do
    resources :correct_answers
    resources :student_answers
    resources :team_answers
    resources :discussions
  end

  resources :student_answers, only: [] do
    collection do
      post :submit
      post :save_score
    end
  end

  resources :discussions do |
|    resources :comments
  end

  resources :users

  resources :var_roles

  resources :courses do
    resources :course_users
    resources :quizzes
  end

  resources :quizzes do
    post :judge_deadline, on: :collection
    resources :codes
  end

  resources :course_users do
    collection { post :import}
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
	has_many :correct_answers, dependent: :destroy
	has_many :student_answers, dependent: :destroy
	has_many :team_answers, dependent: :destroy
	has_many :discussions, dependent: :destroy
	validates :code, presence: true
	belongs_to :quiz

	has_rich_text :code
	has_rich_text :notes

	def correct_answer
		correct_answers.find_by(isCorrect: true)
	end

	def all_correct_answer
		correct_answers.where(isCorrect: true)
	end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :discussion
  # belongs_to :course_user
  has_rich_text :body
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
	belongs_to :code
	has_rich_text :notes
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_users, dependent: :destroy
	has_many :quizzes, dependent: :destroy
	has_many :codes, through: :quizzes
	validates :course_code, uniqueness: true, presence: true
	validates :course_name, uniqueness: true, presence: true
end

app/models/course_user.rb
require 'csv'

class CourseUser < ApplicationRecord
	belongs_to :course
	# validates :uni_ID, uniqueness: true,  presence: true
	# validates :first_name, presence: true

	def self.import(file)
		CSV.foreach(file.path, headers: ['uni_ID', 'last_name', 'first_name', 'academic_program', 'team_id']).drop(1).each do |row|
	      	CourseUser.create! row.to_hash
	    end
	end
end

# CSV.foreach(file.path, headers: true) do |row|

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :code
  has_many :comments, dependent: :destroy
  has_rich_text :code
  has_rich_text :notes
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	belongs_to :course
	has_many :codes, dependent: :destroy
	has_many :student_quizzes
	enum answer_showtime: {"Immediately After Submission": 1, "After Deadline": 2, "4 Days After Deadline": 3 }

	def total_scale
		code_ids = self.codes.ids
		CorrectAnswer.where(code_id: code_ids).where(isCorrect: true).count
	end
	def judge_show
		status = "no"

		if self.answer_showtime == "Immediately After Submission"
			status = "ok"
		elsif self.answer_showtime == "After Deadline"
			status = "ok" if Time.now >= self.deadline
		elsif self.answer_showtime == "4 Days After Deadline"
			status = "ok" if Time.now >= self.deadline+4.days
		end
		status
	end
end

app/models/student_answer.rb
class StudentAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
	# before_save :set_answer_status

	# private
	# def set_answer_status
	# 	if role.blank?||variable.blank?
	# 		self.status = missing
	# 	end
	# 	right_answer = code.correct_answer
	# 	if role == right_answer.role && variable == right_answer.variable
	# 		self.status = :correct
	# 	else
	# 		self.status = :incorrect
	# 	end
	# end
end

app/models/student_quiz.rb
class StudentQuiz < ApplicationRecord
  belongs_to :quiz
end

app/models/team_answer.rb
class TeamAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]
  validates :email, uniqueness: true
	validates :username, uniqueness: true

	def email_required?
    	false
  	end

	def will_save_change_to_email?
    	false
  	end
end

app/models/var_role.rb
class VarRole < ApplicationRecord
	validates :VarRole, uniqueness: true, presence: true
	has_rich_text :example
	has_rich_text :VarRoleDescription
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
	before_action :authenticate_user!
	def index
		@codes = Code.all
	end	

	def show
		@code = Code.find(params[:id])
	end

	def create
		@quiz = Quiz.find(params[:quiz_id])
		@code = @quiz.codes.create(code_params)
		@discussion = @code.discussions.create(code_params)

		redirect_to quiz_path(@quiz)
	end

	def destroy
		@quiz = Quiz.find(params[:quiz_id])
		@code = @quiz.codes.find(params[:id])
		@code.destroy
		
		redirect_to quiz_path(@quiz)
	end

	def update
    	@quiz = Quiz.find(params[:quiz_id])
		@code = @quiz.codes.find(params[:id])
    	@quiz = @code.quiz
		@code.update_attributes(code_params)
		@discussion = @code.discussions.update(code_params)

        redirect_to quiz_path(@quiz)
	end

	private
		def code_params
			params.require(:code).permit(:code, :notes)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-primary"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-danger"
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/var_roles_helper.rb
module VarRolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/codes/_code.html.erb
<td><%= code.code %></td>
<td><%= code.notes %></td>
<td><%= button_tag link_to 'Edit', code_path(code) %>
	<%= button_tag link_to 'Delete', [code.quiz, code], method: :delete, data: {confirm: 'Are you sure?'} %></td><br>
<tr></tr>

app/views/codes/_edit_form.html.erb
<%= form_with(model: [ @code.quiz, @code ], local: true) do |form| %>
  <p>
    <%= form.label 'Enter code here:' %><br>
    <%= form.rich_text_area :code, :cols=>80, :rows=>10 %><br>
    <%= form.label 'Enter question:' %><br>
    <%= form.rich_text_area :notes, :cols=>80, :rows=>5 %><br>
    <%= form.submit "Update"%>
  </p>
<% end %>

<%#= button_tag link_to 'Back', quiz_path(@code.quiz_id) %>

app/views/codes/_form.html.erb
<%= form_with(model: [ @quiz, @quiz.codes.build ], local: true) do |form| %>
  <p>
    <%= form.label 'Enter code here:' %><br>
    <%= form.rich_text_area :code, :cols=>80, :rows=>10 %><br>
    <%= form.label 'Enter question:' %><br>
    <%= form.rich_text_area :notes, :cols=>80, :rows=>5 %><br>
    <%= form.submit "Save code"%>
  </p>
<% end %>

<%= button_tag link_to 'Back', course_path(@quiz.course_id) %>

app/views/codes/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">

            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong>Code:</strong></h1>
			<fieldset>
				<%= @code.code %>
			</fieldset>

			<h1><strong>Question:</strong></h1>
			<fieldset><%= @code.notes %></fieldset>
			<h2>Saved combinations:</h2>
			<table>
				<table border ="1">
				<tr>
					<th>Variable</th>
					<th>Role</th>
					<th>Correct Answer?</th>
					<th>Notes/Explanation</th>
					<th>Action</th>
				</tr>
				<tr><%= render @code.correct_answers %></tr>
			</table>
			<br>

			<h3>Edit Code/Notes</h3>
			<%= render 'edit_form' %>

			<h3>Add new combination</h3>
			<%= render 'correct_answers/form' %>

			<%= button_tag link_to 'Back', quiz_path(@code.quiz_id) %>
        </div>
    </div>
</div>