config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  # get 'welcome/index'

  resources :welcome

  resources :codes do
    resources :correct_answers
    resources :student_answers
    resources :team_answers
    resources :discussions
  end

  resources :student_answers, only: [] do
    collection do
      post :submit
      post :save_score
    end
  end

  resources :discussions do |
|    resources :comments
  end

  resources :users

  resources :var_roles

  resources :courses do
    resources :course_users
    resources :quizzes
  end

  resources :quizzes do
    post :judge_deadline, on: :collection
    resources :codes
  end

  resources :course_users do
    collection { post :import}
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
	has_many :correct_answers, dependent: :destroy
	has_many :student_answers, dependent: :destroy
	has_many :team_answers, dependent: :destroy
	has_many :discussions, dependent: :destroy
	validates :code, presence: true
	belongs_to :quiz

	has_rich_text :code
	has_rich_text :notes

	def correct_answer
		correct_answers.find_by(isCorrect: true)
	end

	def all_correct_answer
		correct_answers.where(isCorrect: true)
	end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :discussion
  # belongs_to :course_user
  has_rich_text :body
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
	belongs_to :code
	has_rich_text :notes
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_users, dependent: :destroy
	has_many :quizzes, dependent: :destroy
	has_many :codes, through: :quizzes
	validates :course_code, uniqueness: true, presence: true
	validates :course_name, uniqueness: true, presence: true
end

app/models/course_user.rb
require 'csv'

class CourseUser < ApplicationRecord
	belongs_to :course
	# validates :uni_ID, uniqueness: true,  presence: true
	# validates :first_name, presence: true

	def self.import(file)
		CSV.foreach(file.path, headers: ['uni_ID', 'last_name', 'first_name', 'academic_program', 'team_id']).drop(1).each do |row|
	      	CourseUser.create! row.to_hash
	    end
	end
end

# CSV.foreach(file.path, headers: true) do |row|

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :code
  has_many :comments, dependent: :destroy
  has_rich_text :code
  has_rich_text :notes
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	belongs_to :course
	has_many :codes, dependent: :destroy
	has_many :student_quizzes
	enum answer_showtime: {"Immediately After Submission": 1, "After Deadline": 2, "4 Days After Deadline": 3 }

	def total_scale
		code_ids = self.codes.ids
		CorrectAnswer.where(code_id: code_ids).where(isCorrect: true).count
	end
	def judge_show
		status = "no"

		if self.answer_showtime == "Immediately After Submission"
			status = "ok"
		elsif self.answer_showtime == "After Deadline"
			status = "ok" if Time.now >= self.deadline
		elsif self.answer_showtime == "4 Days After Deadline"
			status = "ok" if Time.now >= self.deadline+4.days
		end
		status
	end
end

app/models/student_answer.rb
class StudentAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
	# before_save :set_answer_status

	# private
	# def set_answer_status
	# 	if role.blank?||variable.blank?
	# 		self.status = missing
	# 	end
	# 	right_answer = code.correct_answer
	# 	if role == right_answer.role && variable == right_answer.variable
	# 		self.status = :correct
	# 	else
	# 		self.status = :incorrect
	# 	end
	# end
end

app/models/student_quiz.rb
class StudentQuiz < ApplicationRecord
  belongs_to :quiz
end

app/models/team_answer.rb
class TeamAnswer < ApplicationRecord
	belongs_to :code
	enum status: [:correct, :incorrect, :missing]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]
  validates :email, uniqueness: true
	validates :username, uniqueness: true

	def email_required?
    	false
  	end

	def will_save_change_to_email?
    	false
  	end
end

app/models/var_role.rb
class VarRole < ApplicationRecord
	validates :VarRole, uniqueness: true, presence: true
	has_rich_text :example
	has_rich_text :VarRoleDescription
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user!
	# def index
	# 	@courses = Course.all
	# end	

	def index
		if params[:take_quiz] && current_user.username != '1000000'
			# @courses = Course.all
			@courses = Course.joins(:course_users).where(course_users: {uni_id: current_user.username}).order("course_code ASC")
			render 'take_quiz'
		elsif params[:take_quiz] && current_user.username == '1000000'
			@courses = Course.all.order("course_code ASC")
			render 'take_quiz'
		else
			@courses = Course.all.order("course_code ASC")
			render 'index'
		end
	end

	# def show
	# 	@course  = Course.find(params[:id])
	# end

	def show
		if params[:course_quiz] && current_user.username != '1000000'
			@course  = Course.joins(:course_users).where(course_users: {uni_id: current_user.username}).order("course_code ASC").find(params[:id])
			render 'course_quiz'
		elsif params[:course_quiz] && current_user.username == '1000000'
			@course  = Course.find(params[:id])
			render 'course_quiz'
		else
			@course  = Course.find(params[:id])
			render 'show'
		end
	end

	def new
		@course = Course.new
	end

	def edit
		@course = Course.find(params[:id])
	end

	def create
		@course = Course.new(course_params)

		if @course.save
			redirect_to @course
		else
			render 'new'
		end
	end

	def update
		@course = Course.find(params[:id])

		if @course.update(course_params)
			redirect_to @course
		else
			render 'edit'
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy
		redirect_to courses_path
	end

	private
		def course_params
			params.require(:course).permit(:course_code, :course_name)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-primary"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-danger"
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/var_roles_helper.rb
module VarRolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: @course, local:true) do |form| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :course_code, 'Enter Course Code:' %><br>
    <%= form.text_field :course_code, :maxlength=>20 %>
  </p>

  <p>
    <%= form.label :course_name, 'Enter Course Name:' %><br>
    <%= form.text_field :course_name, :maxlength=>80 %>
  </p>
 
  <p>
    <%= form.submit 'Save Course' %>
  </p>
<% end %>

app/views/courses/course_quiz.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?student=true">Home</a></li>
            <li><a href="/courses?take_quiz=true">Quiz</a></li>
            <li><a href="/var_roles?student=true">Variable Roles</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong>Course Details:</strong></h1>
			<p>
				<strong>Course Code:</strong>
				<%= @course.course_code %>
			</p>

			<p>
				<strong>Course Name:</strong>
				<%= @course.course_name %>
			</p><br>

			<h2>Quizzes:</h2>
			<table>
				<table border ="1">
				<tr>
					<th>Quiz Name</th>
					<th>Deadline</th>
					<th>Action</th>
				</tr>
				<tr><% @course.quizzes.each do |quiz| %>
				<td><%= quiz.quiz_name %>
				<td><% if quiz.deadline.nil? %>
				<%= 'No deadline' %>
				<% else %>
				<%= l quiz.deadline %>
				<% end %></td>
				<td>
				<% if (quiz.deadline != nil && DateTime.current < quiz.deadline) || quiz.deadline == nil%>
					<%= button_tag link_to 'Take Quiz', quiz_path(:take_quiz => true, :id => quiz) %>
				<% else %>
					<strong><%= 'Closed'%></strong>
				<% end %>
				</td></tr>	
			<% end %>
			</table><br>

			<%= button_tag link_to 'Back', courses_path(:take_quiz => true) %>
        </div>
    </div>
</div>

app/views/courses/edit.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong>Edit Course</strong></h1>

		<%= render 'form' %>

		<%= link_to 'Home', controller: 'welcome' %>
		<%= link_to 'Back', courses_path %>
        </div>
    </div>
</div>

		

app/views/courses/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">

            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong>Listing Course Records</strong></h1>
			<table>
				<table border ="1">
				<tr>
					<th>Course Code</th>
					<th>Course Name</th>
					<th>Last Updated</th>
					<th>Action</th>
				</tr>

				<% @courses.each do |course| %>
					<tr>
						<td><%= course.course_code %></td>
						<td><%= course.course_name %></td>
						<td><%= l course.updated_at %></td>
						<td><%= button_tag link_to 'Show', course_path(course) %>

						<%= button_tag link_to 'Delete', course_path(course), method: :delete, data: {confirm: 'Are you sure?'} %></td>
					</tr>
				<% end %>
			</table><br>

			<%= button_tag link_to 'Cancel', url_for(:back) %>
			<%= button_tag link_to 'Create New Course', new_course_path %>
        </div>
    </div>
</div>

app/views/courses/new.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong>New Course</strong></h1>

			<%= render 'form' %>

			<%= button_tag link_to 'Home', controller: 'welcome' %>
			<%= button_tag link_to 'Back', courses_path %>
        </div>
    </div>
</div>

			

app/views/courses/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">

            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?teacher=true">Home</a></li>
            <li><a href="/courses">Course</a></li>
            <li><a href="/var_roles?teacher=true">Variable Role</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong>Course Details:</strong></h1>
			<p>
				<strong>Course Code:</strong>
				<%= @course.course_code %>
			</p>

			<p>
				<strong>Course Name:</strong>
				<%= @course.course_name %>
			</p><br>

			<h2>Added Users:</h2>
			<table>
				<table border ="1">
				<tr>
					<th>Uni ID</th>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Team ID</th>
					<th>Action</th>
				</tr>
				<tr><%= render @course.course_users %></tr>
			</table>

			<h3>Add User</h3>
			<%= render 'course_users/form' %>

			<h3>Import User from File</h3>
			<%= form_tag import_course_users_path(course_id: @course.id), local: true, multipart: true do %>
			  <%= file_field_tag :file %>
			  <%= submit_tag "Upload Users" %>
			<% end %>

			<h2>Saved Quizzes:</h2>
			<table>
				<table border ="1">
				<tr>
					<th>Quiz Name</th>
					<th>Deadline</th>
					<th>When To Show Answers</th>
					<th>Individual or Collaborative</th>
					<th>Last Updated</th>
					<th>Action</th>
				</tr>
				<tr><%= render @course.quizzes %></tr>
			</table><br>

			<h3>Add Quiz</h3>
			<%= render 'quizzes/form' %>

			<%= button_tag link_to 'Edit', edit_course_path(@course) %>
			<%= button_tag link_to 'Back', url_for(:back) %>
        </div>
    </div>
</div>

app/views/courses/take_quiz.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        	
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          	</button>
          	<a class="navbar-brand" href="#">Collaborative Code Analysis Tool v0.1</a>
        </div>
    </div>
</nav>
<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/welcome/0?student=true">Home</a></li>
            <li><a href="/courses?take_quiz=true">Quiz</a></li>
            <li><a href="/var_roles?student=true">Variable Roles</a></li>
            <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        <h1><strong>Choose a course</strong></h1>
			<table>
				<table border ="1">
				<tr>
					<th>Course Code</th>
					<th>Course Name</th>
					<th>Action</th>
				</tr>

				<% @courses.each do |course| %>
					<tr>
						<td><%= course.course_code %></td>
						<td><%= course.course_name %></td>
						<td><%= button_tag link_to 'Show', course_path(:course_quiz => true, :id => course.id) %></td>
					</tr>
				<% end %>
			</table><br>

			<%= button_tag link_to 'Home', controller: 'welcome' %>
        </div>
    </div>
</div>

			